CONN SYSTEM/<PASSWORD>;
CON HR/HR;

-- Comenzamos con las funciones
CRETE OR REPLACE FUNCTION FN_SALARIOS(PROD NUMERIC) RETURN NUMBER IS
RESULT NUMBER
BEGIN
SELECT SALARY INTO RESULT FROM EMPLOYEES WHERE 