CONN SYSTEM/<PASSWORD>;
CON HR/HR;

-- POR SI ACASO
SET SERVEROUTPUT ON;

-- Comenzamos con las funciones
CREATE OR REPLACE FUNCTION FN_SALARIOS(PROD NUMERIC) RETURN NUMBER IS
RESULT NUMBER;
BEGIN
SELECT SALARY INTO RESULT FROM EMPLOYEES WHERE EMPLOYEE_ID = PROD;
RETURN(RESULT);
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN 0;
END;
/

DECLARE 
R NUMBER;
BEGIN
R := FN_SALARIOS(1);
DBMS_OUTPUT.PUT_LINE('El salario es: ' || R || ' pesos');
END;
/

-- FUNCION 2
CREATE OR REPLACE FUNCTION FN_GET_SALARY(E_SALARY NUMBER)
RETURN NUMBER IS RESULT NUMBER;
BEGIN
SELECT SALARY INTO RESULT FROM EMPLOYEES
WHERE EMPLOYEE_ID = E_SALARY;
RETURN(RESULT);
EXCEPTION WHEN NO_DATA_FOUND THEN
RETURN 0;
END;
/

DECLARE
V NUMBER;
BEGIN 
V := FN_GET_SALARY(120);
DBMS_OUTPUT.PUT_LINE('El salario es: ' || V);
END;
/

-- FUNCION 3
CREATE OR REPLACE FUNCTION FULL_NAME(EMPID NUMBER) 
RETURN VARCHAR2 IS
LASTNAME EMPLOYEES.LAST_NAME%TYPE;
FIRSTNAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
SELECT LAST_NAME, FIRST_NAME INTO LASTNAME, FIRSTNAME FROM EMPLOYEES
WHERE EMPLOYEE_ID = EMPID;
RETURN('Empleado: ' || EMPID || '-' || UPPER(LASTNAME) || ', ' || UPPER(FIRSTNAME));
END FULL_NAME;
/

DECLARE
EMPID NUMBER := 163;
BEGIN 
DBMS_OUTPUT.PUT_LINE(FULL_NAME(EMPID));
END;
/

-- Funcion 4
CREATE OR REPLACE FUNCTION EMP_SAL_RANKING(EMPID NUMBER) 
RETURN NUMBER IS
MINSAL EMPLOYEES.SALARY%TYPE;
MAXSAL EMPLOYEES.SALARY%TYPE;
JOBID EMPLOYEES.JOB_ID%TYPE;
SAL EMPLOYEES.SALARY%TYPE;
BEGIN
SELECT JOB_ID, SALARY INTO JOBID, SAL FROM EMPLOYEES 
WHERE EMPLOYEE_ID = EMPID;
SELECT MIN(SALARY), MAX(SALARY) INTO MINSAL, MAXSAL FROM EMPLOYEES
WHERE JOB_ID = JOBID;
RETURN ((SAL - MINSAL)/(MAXSAL - MINSAL));
END EMP_SAL_RANKING;
/

DECLARE 
EMPID NUMBER := 163;
BEGIN 
DBMS_OUTPUT.PUT_LINE('The salary ranking for employee ' || EMPID || ' is: ' || ROUND(EMP_SAL_RANKING(EMPID), 2));
END;
/

--FUNCION 5
CREATE OR REPLACE FUNCTION MOSTRAR_EMP 
RETURN NUMBER IS N_EMP NUMBER;
BEGIN
SELECT COUNT(EMPLOYEE_ID) INTO N_EMP FROM EMPLOYEES;
RETURN N_EMP;
END;
/

BEGIN
DBMS_OUTPUT.PUT_LINE('EL TOTAL DE EMPLEADOS ES: ' || MOSTRAR_EMP);
END;
/