CONN SYSTEM/<PASSWORD>;
CON HR/HR;

-- Ejercicios para el uso de PROCEDURE
-- En caso de que esta mal nos dira donde
CREATE OR REPLACE PROCEDURE HOLA_MUNDO IS
L_MENSAJE VARCHAR(100) := '¡HOLA MUNDO!';
BEGIN
DBMS_OUTPUT.PUT_LINE(L_MENSAJE);
END HOLA_MUNDO;
/

-- Para ejecutar un PROCEDURE es
EXECUTE HOLA_MUNDO; --PONER EL PROCEDURE

-- PROCEDURE 2
CREATE OR REPLACE PROCEDURE HOLA_LUGAR(LUGAR_IN IN VARCHAR2) IS
L_MENSAJE VARCHAR2(100);
BEGIN
L_MENSAJE := '¡HOLA ' || LUGAR_IN;
DBMS_OUTPUT.PUT_LINE(HOLA_LUGAR);
END HOLA_LUGAR;
/

EXECUTE HOLA_LUGAR;

