CONN SYSTEM/<PASSWORD>;
CON HR/HR;

-- Ejercicios para el uso de PROCEDURE
-- En caso de que esta mal nos dira donde
CREATE OR REPLACE PROCEDURE HOLA_MUNDO IS
L_MENSAJE VARCHAR(100) := '¡HOLA MUNDO!';
BEGIN
DBMS_OUTPUT.PUT_LINE(L_MENSAJE);
END HOLA_MUNDO;
/

-- Para ejecutar un PROCEDURE es
EXECUTE HOLA_MUNDO; --PONER EL PROCEDURE

-- PROCEDURE 2
/*Aqui le llega un parametro a la hora de hacer un execute
y eso hace que la funcion tome el valor y lo muestre cuando se usa*/
CREATE OR REPLACE PROCEDURE HOLA_LUGAR(LUGAR_IN IN VARCHAR2) IS
l_mensaje VARCHAR2(100);
BEGIN
l_mensaje := '¡HOLA ' || LUGAR_IN;
DBMS_OUTPUT.PUT_LINE(l_mensaje);
END HOLA_LUGAR;
/

EXECUTE HOLA_LUGAR;

-- uso de PROCEDURE 2
BEGIN
HOLA_LUGAR('SALTILLO!');
HOLA_LUGAR('COAHUILA!');
END;
/

-- PROCEDURE 3
/*Pide dos numeros para insertar en el procedimiento*/
CREATE OR REPLACE PROCEDURE ACT_SALARIO(EMPID NUMBER, SAL NUMBER) IS
BEGIN
UPDATE EMPLOYEES SET SALARY = SAL 
WHERE EMPLOYEE_ID = EMPID;
DBMS_OUTPUT.PUT_LINE('El empleado: ' || EMPID || ' tiene un salario de: ' || SAL);
END;
/

EXECUTE ACT_SALARIO(120, 2000);

-- PROCEDURE 4
CREATE OR REPLACE PROCEDURE PAR_IN_OUT(EMP IN NUMBER, SAL OUT NUMBER) IS
BEGIN 
SELECT SALARY INTO SAL FROM EMPLOYEES 
WHERE EMPLOYEE_ID = EMP;
END;
/

DECLARE
SALARIO NUMBER;
BEGIN
PAR_IN_OUT(100, SALARIO);
DBMS_OUTPUT.PUT_LINE('EL SALARIO DEL EMPLEADO 100 ES: ' || SALARIO);
END;
/

-- PROCEDURE 5 PERTENECE A FUERAD DE HR
CREATE OR REPLACE PROCEDURE DISPONIBILIDAD(ID_PROD IN NUMBER) AS
V_STOCK NUMBER;
BEGIN
SELECT STOCK INTO V_STOCK FROM PRODUCTORA WHERE CODIGO = ID_PROD;
IF V_STOCK = 5 THEN
DBMS_OUTPUT.PUT_LINE('El producto: ' || ID_PROD || ' tiene el stock lleno');
ELSE
IF V_STOCK < 5 THEN
DBMS_OUTPUT.PUT_LINE('El producto: ' || ID_PROD || ' aun tiene espacios');
END IF;
END IF;
END;
/


-- PROCEDURE 6
CREATE OR REPLACE PROCEDURE SALARIO_COMISION IS
BEGIN 
UPDATE EMPLOYEES SET SALARY = SALARY*2
WHERE COMMISSION_PCT IS NULL;
END SALARIO_COMISION;
/