CONN system/<password>
conn <practica1>

CONN HR/HR;

-- Usando las mayusculas le damos un ALIAS a las tablas para que escribamos menos
SELECT COUNT(EMPLOYEE_ID), JOB_TITLE FROM EMPLOYEES E, JOBS J
WHERE J.JOB_ID = E.JOB_ID
GROUP BY JOB_TITLE;

-- nueva funcion 
SET LINESIZE 150 --establecerá el ancho de línea para la salida de las consultas a 150 caracteres.
RUN -- muestra la ultima funcion

/*muestra primer nombre, nombre del departamento y la ciudad que se encuentre*/
SELECT FIRST_NAME, DEPARTMENT_NAME, CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID;

--
SELECT FIRST_NAME, DEPARTMENT_NAME, CITY FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID;

--
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_TITLE FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID = J.JOB_ID ORDER BY EMPLOYEE_ID;

-- UNIMOS EL PAIS Y CONTINENTE 
SELECT COUNTRY_NAME "PAISES", REGION_NAME "CONTINENTE" FROM COUNTRIES, REGIONS
WHERE COUNTRIES.REGION_ID = REGIONS.REGION_ID ORDER BY COUNTRY_NAME;

SELECT DEPARTMENT_NAME, COUNTRY_NAME FROM DEPARTMENTS D, LOCATIONS L, COUNTRIES C
WHERE D.LOCATION_ID = L.LOCATION_ID AND L.COUNTRY_ID = C.COUNTRY_ID;

