CONN SYSTEM/<PASSWORD>

CONN HR/HR

/*Comencemos con el aparteado de subconsultas en sql*/
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
WHERE JOB_ID = (SELECT JOB_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 100);

