conn system/<contrasña>
create user <nombre-practica> identified by <nombre-practica>;
grant connect, resource to <nomnbre-practica>;
conn <nombre-practica>;

CREATE TABLE ALUMNOS (
  NUM_CONTROL NUMERIC(15) NOT NULL,
  NOMBRE  VARCHAR(20) NULL,
  APELLIDO VARCHAR(20) NULL,
  FECHA  DATE NULL,
  CONSTRAINT PK_NUMERO_CONTROL PRIMARY KEY(NUM_CONTROL)
);

CREATE TABLE PROFESORES  (
  ID_PROF NUMERIC(8) NOT NULL,
  NOMBRE VARCHAR(40) NULL,
  DIRECCION VARCHAR(20) NULL,
  TELEFONO NUMERIC(10) NULL,
  CONSTRAINT PK_ID_PROFESOR PRIMARY KEY(ID_PROF)
);

CREATE TABLE MODULOS (
  CODIGO  NUMERIC(8) NOT NULL,
  ID_PROF NUMERIC(8) NOT NULL,
  NOMBRE VARCHAR(25) NULL,
  CONSTRAINT PK_CODIGO PRIMARY KEY(CODIGO )
);

CREATE TABLE MODULOS_has_ALUMNOS (
  CODIGO  NUMERIC(8) NOT NULL,
  NUM_CONTROL NUMERIC(15) NOT NULL,
  DELEGADO VARCHAR(20) NULL,
  CONSTRAINT PK_AMBAS PRIMARY KEY(CODIGO , NUM_CONTROL),
  CONSTRAINT FK_CODIGO FOREIGN KEY(CODIGO) REFERENCES MODULOS(CODIGO),
  CONSTRAINT FK_NUM_CON FOREIGN KEY(NUM_CONTROL) REFERENCES ALUMNOS(NUM_CONTROL)
);