conn system/<contrasña>
create user <nombre-practica> identified by <nombre-practica>;
grant connect, resource to <nomnbre-practica>;
conn <nombre-practica>;


CREATE TABLE PROVEDORES (
  RFC VARCHAR(20) NOT NULL,
  NOMBRE VARCHAR(20) NULL,
  DIRECCION VARCHAR(20) NULL,
  PRIMARY KEY(RFC)
);

CREATE TABLE CLIENTES (
  ID_CLIENTES NUMERIC(20) NOT NULL,
  NOMBRES VARCHAR(20) NULL,
  APELLIDOS VARCHAR(20) NULL,
  DIRECCION VARCHAR(20) NULL,
  FECH_NAC DATE NULL,
  PRIMARY KEY(ID_CLIENTES)
);

CREATE TABLE PRODUCTORAS (
  CODIGO NUMERIC(20) NOT NULL,
  RFC VARCHAR(20) NOT NULL,
  NOMBRE VARCHAR(20) NULL,
  PRECIO NUMERIC(5) NULL,
  PRIMARY KEY(CODIGO)
);

CREATE TABLE CLIENTES_has_PRODUCTORAS (
  ID_CLIENTES NUMERIC(20) NOT NULL,
  CODIGO NUMERIC(20) NOT NULL,
  PRIMARY KEY(ID_CLIENTES, CODIGO)
);


ALTER TABLE CLIENTES_has_PRODUCTORAS
ADD CONSTRAINT FK_IDCLIENTES 
FOREIGN KEY(ID_CLIENTES)
REFERENCES CLIENTES(ID_CLIENTES);

ALTER TABLE CLIENTES_has_PRODUCTORAS
ADD CONSTRAINT FK_CODIGO 
FOREIGN KEY(CODIGO)
REFERENCES CLIENTES(CODIGO);

ALTER TABLE PRODUCTORAS 
ADD CONSTRAINT FK_RFC 
FOREIGN KEY(RFC)
REFERENCES PROVEDORES(RFC)