conn system/<contrasña>
create user <nombre-practica> identified by <nombre-practica>;
grant connect, resource to <nomnbre-practica>;
conn <nombre-practica>;

CREATE TABLE CAMIONERAS (
  ID_CAMIONERAS NUMERIC(10) NOT NULL,
  NUM_CAM VARCHAR(20) NULL,
  TELEFONO  NUMERIC(8) NULL,
  DIR_CAN VARCHAR(20) NULL,
  SALARIO NUMERIC(6) NULL,
  POBLACION VARCHAR(20) NULL,
  CONSTRAINT PK_ID_CAMIONERAS PRIMARY KEY(ID_CAMIONERAS)
);

CREATE TABLE CAMIONES (
  MATRICULA VARCHAR(7) NOT NULL,
  MODELO  VARCHAR(20) NULL,
  TIPOS VARCHAR(20) NULL,
  POTENCIA VARCHAR(20) NULL,
  CONSTRAINT PK_MATRICULAS PRIMARY KEY(MATRICULA)
);

CREATE TABLE CAMIONERAS_has_CAMIONES (
  MATRICULA VARCHAR(7) NOT NULL,
  ID_CAMIONERAS NUMERIC(10) NOT NULL,
  CONSTRAINT PK_AMBAS PRIMARY KEY(MATRICULA, ID_CAMIONERAS),
  CONSTRAINT FK_MATRICULA FOREIGN KEY(MATRICULA) REFERENCES CAMIONES(MATRICULA),
  CONSTRAINT FK_ID_CAMIONERAS FOREIGN KEY(ID_CAMIONERAS) REFERENCES CAMIONERAS(ID_CAMIONERAS)
);

CREATE TABLE PROVINCIAS (
  COD_PROV NUMERIC(6) NOT NULL,
  NOMBRE VARCHAR(20) NULL,
  CONSTRAINT PK_COD_PROV PRIMARY KEY(COD_PROV)
);

CREATE TABLE PAQUETES (
  CODIGO NUMERIC(20) NOT NULL,
  COD_PROV NUMERIC(6) NOT NULL,
  ID_CAMIONERAS NUMERIC(10) NOT NULL,
  DESCRIPCION VARCHAR(20) NULL,
  DESTINATARIO VARCHAR(20) NULL,
  DIR_DES VARCHAR(20) NULL,
  CONSTRAINT PK_CODIGO PRIMARY KEY(CODIGO)
);