CONN SYSTEM/<password>
CONN HR/HR;

--FORMA DE DAR PERISOS
GRANT SELECT ON EMPLOYEES TO EJ12023U1;
GRANT UPDATE ON EMPLOYEES TO EJ12023U1;
GRANT INSERT ON EMPLOYEES TO EJ12023U1;
GRANT DELETE ON EMPLOYEES TO EJ12023U1;

--PARA QUITAR PERMISOS
GRAN REVOKE SELECT ON HR.EMPLOYYES FROM EJ12023U1L
GRAN REVOKE UPDATE ON HR.EMPLOYYES FROM EJ12023U1L
GRAN REVOKE INSERT ON HR.EMPLOYYES FROM EJ12023U1L
GRAN REVOKE DELETE ON HR.EMPLOYYES FROM EJ12023U1L

--CREACION DE ROLES
CRETE ROLE CREADORCUENTAS;

-- PRIVILEGIOS AL ROL
GRANT CREAT SESSION, CREATE USER TO CREADORCUENTAS;

CREATE CREADORCUENTAS BY US_CREADOR
DEFAULT TABLESPACE ESPACIO1
TEMPORARY TABLESPACE TEMP_ESPACIO1
QUOTA 5K ON ESPACIO1;

-- DAMOS AL USARIO QUE QUEREMOS EL ROL QUE REQUIERA
GRAN CREADORCUENTAS TO US_CREADOR;

CREATE USER ADMINISTRADOR IDENTIFIED BY ADMINISTRADOR
DEFAULT TABLASPACES USER TEMPORARY
TABLESPACE TEMP
QUOTA 500K ON USERS;

SELECT GRANTEE, PRIVILEGE FROM DBA_SYS_PRIV WHERE GRANTEE = 'ADMINISTRADOR';

SELECT GRANTEE, GRANTED_ROLE FROM DBA_ROLE_PRIV WHERE GRANTEE = 'ADMINSTRADOR';

SELECT GRANTEE, PRIVILEGE FROM DBA_TAB_PRIV WHERE GRANTEE = 'ADMINISTRADOR'

GRANT CREATE SESSION TO ADMINISTRADOR;

SELECT GRANTEE, PRIVILEGE FROM DBA_SYS_PRIV WHERE GRANTEE = 'ADMINISTRADOR'; --AHORA DEBERIA FUNCIONAR

GRANT CREATE ROLE TO ADMINISTRADOR;

CONN ADMINISTRADOR/ADMINISTRADOR

CREATE ROLE MANAGER;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCDEDURE TO MANAGER;

CREATE USER USUARIO1 IDENTIFIED BY USUARIO1
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 500K ON USERS;
GRANT SELECT ON EJ1202310.CLIENTES TO USUARIO1;