CONN system/<password>

-- Creamos un nuevo perfil 
CREATE PROFILE CLERK LIMIT --CREAMOS UN PERFIL CON UN LIMITE 
SESSIONS_PER_USER 1 --LIMITA EL NUMERO DE SESIONES SIMULTANEAS
IDLE_TIME 30 --TIEMPO LIMITE DE INACTIVIDAD 
CONNECT_TIME 600; --TIEMPO LIMITE DE ACTIVIDAD

CREATE USER JOHNY IDENTIFIED BY LTC 
DEFAULT TABLESPACE USERS --crea un area de trabajo predeterminado 
TEMPORARY TABLESPACE USERS --crea la tabla temporal 
QUOTA SK ON USERS --declare el limite de espacio para trabajar del usuario
PROFILE CLERK; --al usuario para establecer ciertos límites y restricciones en su uso de la base de datos.

CREATE PROFILE ADMIN LIMIT
SESSIONS_PER_USER 1
IDLE_TIME 30
CONNECT_TIME 600;

ALTER USER JOHNY PROFILE ADMIN;

CREATE TABLESPACE ESPACIO1 DATAFILE 'C:\TABLASPACES/ESPACIO1.DBF'
AUTOEXTEND ON NEXT 200K MAXSIZE 1400K
DEFAULT STORAGE(INITIAL 16K NEXT 16K MINEXTENTS 1 MAXEXTENTS 3);

-- Mejor forma de verlo
CREATE TEMPORARY TABLESPACE TEMP_ESPACIO1 
TEMPFILE 'C:\\TABLASPACES\\TEMP_ESPACIO1.DBF'
SIZE 50K 
AUTOEXTEND ON 
NEXT 50K 
MAXSIZE 600K 
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 100K;