CREATE TABLE ALUMNOS (
  NUM_CON NUMERIC(8) NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(25) NULL,
  APELLIDOP VARCHAR(20) NULL,
  APELLIDOM VARCHAR(20) NULL,
  CORREO VARCHAR(30) NULL,
  PRIMARY KEY(NUM_CON)
);

CREATE TABLE MATERIAS (
  ID_MATERIA INTEGER(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(20) NULL,
  DESCRIPCION VARCHAR(30) NULL,
  PRIMARY KEY(ID_MATERIA)
);

CREATE TABLE PROFESORES (
  MATRICULA INTEGER(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(20) NULL,
  APELLIDOP VARCHAR(20) NULL,
  APELLIDOM VARCHAR(20) NULL,
  CORREO VARCHAR(20) NULL,
  PRIMARY KEY(MATRICULA)
);


CREATE TABLE ALUMNOS_has_MATERIAS (
  ID_MATERIA INTEGER(3) UNSIGNED NOT NULL,
  NUM_CON NUMERIC(8) NOT NULL,
  CALIFICACION NUMERIC(2) NULL,
  PRIMARY KEY(ID_MATERIA, NUM_CON)
);

CREATE TABLE PROFEMATERIA (
  ID_PROF_MAT INTEGER(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_MATERIA INTEGER(3) UNSIGNED NOT NULL,
  MATRICULA INTEGER(5) UNSIGNED NOT NULL,
  PRIMARY KEY(ID_PROF_MAT)
);
