CONN SYSTEM/<password>

CREATE USER ESCUELA IDENTIFIED BY ESCUELA; 
GRANT CONNECT, RESOURCE TO ESCUELA;
CONN ESCUELA/ESCUELA

CREATE TABLE ALUMNOS (
  NUM_CON NUMERIC(8) NOT NULL,
  NOMBRE VARCHAR(25) NULL,
  APELLIDOP VARCHAR(20) NULL,
  APELLIDOM VARCHAR(20) NULL,
  CORREO VARCHAR(40) NULL,
  CONSTRAINT PK_NUM_CON PRIMARY KEY(NUM_CON)
);

CREATE TABLE MATERIAS (
  ID_MATERIA INTEGER NOT NULL,
  NOMBRE VARCHAR(20) NULL,
  DESCRIPCION VARCHAR(30) NULL,
  CONSTRAINT PK_ID_MATERIA PRIMARY KEY(ID_MATERIA)
);

CREATE TABLE PROFESORES (
  MATRICULA INTEGER NOT NULL,
  NOMBRE VARCHAR(20) NULL,
  APELLIDOP VARCHAR(20) NULL,
  APELLIDOM VARCHAR(20) NULL,
  CORREO VARCHAR(40) NULL,
  CONSTRAINT PK_MATRICULA PRIMARY KEY(MATRICULA)
);

CREATE TABLE ALUMNOS_has_MATERIAS (
  ID_MATERIA INTEGER NOT NULL,
  NUM_CON NUMERIC(8) NOT NULL,
  CALIFICACION NUMERIC(2) NULL,
  PRIMARY KEY(ID_MATERIA, NUM_CON),
  CONSTRAINT FK_NUM_CON FOREIGN KEY(NUM_CON) REFERENCES ALUMNOS(NUM_CON),
  CONSTRAINT FK_ID_MATERIA FOREIGN KEY(ID_MATERIA) REFERENCES MATERIAS(ID_MATERIA)
);

CREATE TABLE PROFEMATERIA (
  ID_PROF_MAT INTEGER NOT NULL,
  ID_MATERIA INTEGER NOT NULL,
  MATRICULA INTEGER NOT NULL,
  CONSTRAINT PK_ID_PROF_MAT PRIMARY KEY(ID_PROF_MAT),
  CONSTRAINT FK_MATERIA FOREIGN KEY(ID_MATERIA) REFERENCES MATERIAS(ID_MATERIA),
  CONSTRAINT FK_MATRICULA_PM FOREIGN KEY(MATRICULA) REFERENCES PROFESORES(MATRICULA)
);

CREATE TABLE USUARIOS (
    USUARIO VARCHAR(30) NOT NULL,
    PASS VARCHAR(30) NULL,
    CONSTRAINT FK_USER PRIMARY KEY(USUARIO)
);


-- Sentencias para ingreso de registros de tablas}

INSERT INTO PROFESORES (MATRICULA, NOMBRE, APELLIDOP, APELLIDOM, CORREO) VALUES (9105147, 'Jose', 'Morales', 'Zuñiga', 'jmz@mail.com');

INSERT INTO ALUMNOS (NUM_CON, NOMBRE, APELLIDOP, APELLIDOM, CORREO) VALUES (2009852, 'Maria', 'Niov', 'Goto', 'mng@es.com');

INSERT INTO MATERIAS(ID_MATERIA, NOMBRE, DESCRIPCION) VALUES (0001, 'Fisica', 'Ciencias basicas');