CONN SYSTEM/<password>
CONN HR/HR

-- Tema de los operadores SET

/*Union de tablas*/
SELECT REGION_ID, REGION_NAME FROM REGIONS UNION
SELECT REGION2_ID, REGION_NAME FROM REGIONS2
ORDER BY REGION_ID;

SELECT REGION_ID, REGION_NAME, FROM REGIONS
UNION ALL
SELECT REGION2_ID, REGION_NAME, REGIONS2
ORDER BY REGION_ID;

-- INSERCCION
SELECT REGION_ID, REGION_NAME, FROM REGIONS
INSERT
SELECT REGION2_ID, REGION_NAME FROM REGIONS2
ORDER BY REGION_ID;