CONN SYSTEM/<password>
CON HR/HR

-- VISTAS AYUDAN A TRAER SELECTS ECHOS CON UN ESPECIE DE ALIAS
CREATE OR REPLACE VIEW VISTA1 AS
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES;

-- ASI VEMOS LA VISTA CREADA
SELECT * FROM VISTA1; 

-- VISTA2
CREATE OR REPLACE VIEW VISTA2 AS
SELECT EMPLOYEE_ID EMP, FIRST_NAME NOMBRE, HIRE_DATE INGRESO FROM EMPLOYEES;

-- Vistac
CREATE OR REPLACE VIEW VISTAC(CATEGORIA, MIN, MAX) AS 
SELECT JOB_TITLE, MIN(HIRE_DATE), MAX(HIRE_DATE) FROM EMPLOYEES, JOBS
GROUP BY JOB_TITLE
ORDER BY JOB_TITLE;

SELECT * FROM VISTAC;

-- Vistasist
/*la ultima linea garantizar que cualquier operación de inserción o 
actualización en la vista cumpla con esta condición. */
CREATE OR REPLACE VIEW VISTASIST AS
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60
WITH CHECK OPTION CONSTRAINT CK_SISTEMAS;

--Vista vistaLectura 
/*el uso de whith sirve solo para dar permiso de lectura a la vista*/
CREATE OR REPLACE VIEW VISTALECTURA AS
SELECT FIRST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60
WITH READ ONLY;


SELECT * FROM VISTALECTURA;

-- Vista employees_view
CREATE OR REPLACE VIEW EMPLOYEES_VIEW AS
SELECT EMPLOYEE_ID, LAST_NAME "EMPLEADO", DEPARTMENT_ID
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES_VIEW;

-- Seleccion de vista, atributo y que provenga de una vista
SELECT EMPLEADO, DEPARTMENT_ID FROM EMPLOYEES_VIEW;

-- vista depto50
CREATE OR REPLACE VIEW DEPTO50 AS
SELECT EMPLOYEE_ID "EMPNO", LAST_NAME "EMPLEADO", DEPARTMENT_ID "DEPTNO" FROM EMPLOYEES
WHERE EMPLOYEE_ID = 50;

-- Vista salario_view
CREATE OR REPLACE VIEW SALARIO_VIEW AS
SELECT LAST_NAME "EMPLEADO", DEPARTMENT_NAME "DEPARTAMENTO", SALARY "SALARIO", JOB_TITLE "CATEGORIA"
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.JOB_ID = J.JOB_ID;

SELECT * FROM SALARIO_VIEW;
DESC SALARIO_VIEW;

-- Vista VISTA_GENERAL
/*
Crear una vista llamada VISTA_GENERAL que contenga el id del empleado, nombre,
 salario, nombre del departamento, la localidad donde está el departamento, asi como el
  nombre de la región, la ciudad y el nombre del cargo*/

CREATE OR REPLACE VIEW VISTA_GENERAL(ID_EMP, NOMBRE, SALARIO, NOM_DPTO, LOCALIDAD, NOM_REGION, CIUDAD, NOM_CARGO) AS
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_NAME, CITY, REGION_NAME, CITY, JOB_TITLE
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L, COUNTRIES C, REGIONS R, JOBS J
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND L.COUNTRY_ID = C.COUNTRY_ID AND
C.REGION_ID = R.REGION_ID AND E.JOB_ID = J.JOB_ID;

--VISTA_EMPLEADO
CREATE OR REPLACE VIEW VISTA_EMPLEADO AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_NAME, JOB_TITLE, HIRE_DATE, PHONE_NUMBER 
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
WHERE E.JOB_ID = J.JOB_ID AND E.DEPARTMENT_ID = D.DEPARTMENT_ID;

